name: shared.yml
on:
  push:
    paths:
      - TestGenerator.Shared/*.csproj

jobs:
  build:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup .Net
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          
      - name: Build
        run: |
          mkdir nuget
          dotnet pack TestGenerator.Shared -o nuget
          
      - name: Publish on nuget.org
        run: |
          dotnet nuget push nuget/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }}
